# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disappointed_fan_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Search',
            new_name='UserSearch',
        ),
    ]
